# Generated by Django 5.2 on 2025-05-20 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('deliverables', models.TextField()),
                ('deadline', models.DateField()),
                ('m1_title', models.CharField(blank=True)),
                ('m1', models.TextField(blank=True)),
                ('m2_title', models.CharField(blank=True)),
                ('m2', models.TextField(blank=True)),
                ('m3_title', models.CharField(blank=True)),
                ('m3', models.TextField(blank=True)),
                ('m4_title', models.CharField(blank=True)),
                ('m4', models.TextField(blank=True)),
                ('m5_title', models.CharField(blank=True)),
                ('m5', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
