# Generated by Django 5.2 on 2025-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_assigned_to_project_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
