# Generated by Django 5.2 on 2025-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_assigned_to_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_by',
            field=models.CharField(max_length=255),
        ),
    ]
