# Generated by Django 5.2 on 2025-04-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=111)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Membership',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_id', to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_Ids', to='users.classrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('ass_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=111)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.classrooms')),
            ],
        ),
    ]
